/* Portfolio content — easily editable defaults */
const PORTFOLIO = {
  identity: {
    name: "AARON ARCHER",
    handle: "aaron_archer",
    host: "architsec",
    title: "Cybersecurity Engineer & DevSecOps Consultant",
    tagline: "Securing systems. Hardening pipelines. Engineering trust.",
    bio: "I architect end-to-end security for organizations that cannot afford to fail. With a decade spanning offensive research, secure software development, and DevSecOps automation, I help teams ship faster — without shipping vulnerabilities. I specialize in cloud-native security, supply-chain integrity, and communications protection.",
    location: "Remote · Worldwide",
    status: "Available for new engagements",
    yearsExperience: 10,
  },
  contact: [
    { label: "Email",    icon: "envelope",   value: "aaron@architsec.io",            href: "mailto:aaron@architsec.io" },
    { label: "GitHub",   icon: "github",     value: "github.com/aaronarcher",       href: "https://github.com/" },
    { label: "LinkedIn", icon: "linkedin",   value: "linkedin.com/in/aaron-archer",  href: "https://linkedin.com/" },
    { label: "Signal",   icon: "broadcast",  value: "@aaron.42",                     href: "#" },
    { label: "PGP",      icon: "key",        value: "0xA1B2 C3D4 E5F6 7890",        href: "#" },
  ],
  rotatingRoles: [
    "Penetration Tester",
    "Secure Software Engineer",
    "DevSecOps Architect",
    "Comms Security Specialist",
    "Red Team Operator",
  ],
  stats: [
    { value: "10",   unit: "yrs", label: "Field Experience" },
    { value: "47",   unit: "+",   label: "Engagements" },
    { value: "12",   unit: "",    label: "CVEs Disclosed" },
    { value: "100%", unit: "",    label: "Audit Pass Rate" },
  ],
  skills: [
    {
      title: "Offensive Security",
      sub: "Red team · Penetration testing",
      icon: "bug",
      items: [
        { name: "Burp Suite Pro",          level: 95 },
        { name: "Nmap / Masscan",          level: 92 },
        { name: "Metasploit Framework",    level: 88 },
        { name: "Cobalt Strike",           level: 80 },
        { name: "Active Directory Attacks",level: 86 },
      ],
      tags: ["OSCP", "OSEP", "CRTO", "Mythic", "Sliver"],
    },
    {
      title: "Cloud Security",
      sub: "AWS · GCP · Azure hardening",
      icon: "cloud-lock",
      items: [
        { name: "AWS (IAM, GuardDuty, KMS)", level: 94 },
        { name: "GCP (IAP, SCC, Workload ID)", level: 86 },
        { name: "Azure (Defender, Sentinel)", level: 78 },
        { name: "Kubernetes Hardening",       level: 90 },
        { name: "Container Image Scanning",   level: 88 },
      ],
      tags: ["CIS", "NIST 800-53", "STIG", "CSPM"],
    },
    {
      title: "DevSecOps",
      sub: "Shift-left · Pipeline security",
      icon: "diagram-3",
      items: [
        { name: "GitHub Actions / GitLab CI", level: 95 },
        { name: "Terraform / OpenTofu",       level: 92 },
        { name: "SAST / DAST / SCA",          level: 90 },
        { name: "Sigstore / SLSA",            level: 84 },
        { name: "Policy-as-Code (OPA)",       level: 80 },
      ],
      tags: ["Trivy", "Semgrep", "Snyk", "tfsec", "Checkov"],
    },
    {
      title: "Secure Software Dev",
      sub: "Architecture · Code review",
      icon: "shield-lock",
      items: [
        { name: "Threat Modeling (STRIDE)",  level: 93 },
        { name: "Cryptography Engineering",  level: 88 },
        { name: "Secure Code Review",        level: 92 },
        { name: "Zero-Trust Architecture",   level: 85 },
        { name: "OWASP Top 10 / ASVS",       level: 96 },
      ],
      tags: ["mTLS", "OAuth/OIDC", "JWT", "SBOM", "Vault"],
    },
    {
      title: "Languages & Runtime",
      sub: "Polyglot by necessity",
      icon: "code-slash",
      items: [
        { name: "Python",  level: 95 },
        { name: "Go",      level: 88 },
        { name: "Rust",    level: 72 },
        { name: "Bash",    level: 92 },
        { name: "TypeScript", level: 84 },
      ],
      tags: ["FastAPI", "gRPC", "Node", "C", "PowerShell"],
    },
    {
      title: "Comms Security",
      sub: "OPSEC · Encrypted channels",
      icon: "broadcast-pin",
      items: [
        { name: "End-to-End Encryption",     level: 90 },
        { name: "Signal / Matrix Protocols", level: 86 },
        { name: "VPN / WireGuard",           level: 92 },
        { name: "Hardware Tokens (YubiKey)", level: 88 },
        { name: "Operational Security",      level: 94 },
      ],
      tags: ["GPG", "TLS 1.3", "Noise", "Tor", "Tails"],
    },
  ],
  projects: [
    {
      name: "ARCHITSEC Homelab",
      year: "2026",
      status: "ongoing",
      category: "homelab",
      description: "Production-grade on-premises / cloud hybrid lab — Proxmox VE on Dell R630, 8-VLAN segmented network, dual-DC Active Directory domain, 3-node K3s Kubernetes cluster, NATS JetStream messaging, GitLab CI/CD, Harbor registry, Wazuh SIEM, Keycloak SSO, and HashiCorp Vault. Full topology, hardware inventory, and build log documented below.",
      tags: ["Proxmox VE", "K3s", "WireGuard", "GitLab CI", "Wazuh", "Vault", "Keycloak", "FreshTomato"],
      links: [{ label: "full documentation", href: "#homelab" }],
    },
    {
      name: "Sentinel Pipeline",
      year: "2025",
      status: "ongoing",
      category: "devsecops",
      description: "End-to-end shift-left security platform that integrates SAST, DAST, SCA, IaC scanning, and SLSA attestation into CI/CD pipelines. Reduced mean time to remediate vulnerabilities by 73% across pilot teams.",
      tags: ["Go", "GitHub Actions", "Sigstore", "SLSA", "OPA"],
      links: [{ label: "case study", href: "#" }, { label: "github", href: "#" }],
    },
    {
      name: "Cipher Vault",
      year: "2024",
      status: "complete",
      category: "secdev",
      description: "Open-source secrets management server with hardware-backed root-of-trust, automatic rotation, and zero-knowledge audit trails. Production-deployed at three Fortune 500 financial institutions.",
      tags: ["Rust", "HSM", "AES-256-GCM", "TPM", "mTLS"],
      links: [{ label: "github", href: "#" }, { label: "whitepaper", href: "#" }],
    },
    {
      name: "BlackICE Lab",
      year: "2024",
      status: "complete",
      category: "offsec",
      description: "Red team adversary emulation framework simulating APT29, FIN7, and Lazarus TTPs. Used by 8 enterprise SOCs for purple-team exercises and detection engineering.",
      tags: ["Python", "MITRE ATT&CK", "Sliver", "C2", "EDR-evasion"],
      links: [{ label: "demo", href: "#" }],
    },
    {
      name: "Aegis Kubernetes Bench",
      year: "2024",
      status: "complete",
      category: "cloud",
      description: "Hardened Kubernetes reference platform — eBPF runtime security, Falco/Tetragon detection, Cilium network policies, and CIS-K8s compliance out of the box.",
      tags: ["Kubernetes", "eBPF", "Cilium", "Falco", "Terraform"],
      links: [{ label: "docs", href: "#" }, { label: "github", href: "#" }],
    },
    {
      name: "Comms Relay",
      year: "2023",
      status: "complete",
      category: "comms",
      description: "Self-hosted Matrix federation deployment for an NGO operating in high-risk regions. End-to-end encrypted messaging with PFS, hardware tokens, and Tor egress.",
      tags: ["Matrix", "WireGuard", "Tor", "Ansible", "Hardening"],
      links: [{ label: "case study", href: "#" }],
    },
    {
      name: "Zero-Day Disclosure: CVE-2023-XXXXX",
      year: "2023",
      status: "archived",
      category: "offsec",
      description: "Authentication bypass in a widely-deployed IoT firmware affecting >2M devices. Coordinated disclosure resulted in fleet-wide remediation in 21 days.",
      tags: ["Firmware", "Reverse Engineering", "CVE", "Coordinated Disclosure"],
      links: [{ label: "advisory", href: "#" }],
    },
    {
      name: "PolicyForge",
      year: "2022",
      status: "complete",
      category: "devsecops",
      description: "Policy-as-Code authoring studio for OPA/Rego with live test harness, fuzz-generated test cases, and SCM-integrated change review. Adopted by 30+ engineering teams.",
      tags: ["TypeScript", "Rego", "OPA", "WASM", "Monaco"],
      links: [{ label: "github", href: "#" }, { label: "live", href: "#" }],
    },
    {
      name: "Threat Model Studio",
      year: "2022",
      status: "complete",
      category: "secdev",
      description: "Collaborative STRIDE threat-modeling tool integrated with Jira and GitHub Issues — bridges security architects and product engineering teams.",
      tags: ["React", "STRIDE", "GraphQL", "Postgres"],
      links: [{ label: "demo", href: "#" }],
    },
  ],
  certifications: [
    { name: "OSCP",  org: "Offensive Security", year: "2021", icon: "shield-shaded" },
    { name: "OSEP",  org: "Offensive Security", year: "2023", icon: "shield-fill-check" },
    { name: "CISSP", org: "(ISC)²",             year: "2022", icon: "patch-check" },
    { name: "AWS Certified Security – Specialty", org: "Amazon Web Services", year: "2024", icon: "cloud-check" },
    { name: "CKS — Certified Kubernetes Security", org: "Linux Foundation / CNCF", year: "2024", icon: "diagram-2" },
    { name: "CRTO", org: "Zero-Point Security", year: "2023", icon: "bullseye" },
    { name: "GCIH", org: "GIAC / SANS", year: "2021", icon: "exclamation-shield" },
    { name: "CompTIA Security+ (CE)", org: "CompTIA", year: "2019", icon: "shield-plus" },
  ],
  achievements: [
    "Spoke at DEF CON 31 — Cloud Village (2023)",
    "12 published CVEs in enterprise firmware and OSS",
    "Top 50 — HackTheBox global ranking (2022)",
    "Built and led a 14-engineer red team",
    "Maintainer of three OWASP project chapters",
    "Open-source contributions to Sigstore and OPA",
  ],
  education: [
    {
      kind: "teal",
      date: "2018 — 2020",
      title: "M.S. Cybersecurity",
      org: "Carnegie Mellon University · Heinz College",
      detail: "Specialization in cryptographic engineering and software security. Thesis: \"Verifiable Provenance in Software Supply Chains\" — adopted as a reference architecture by two enterprise customers.",
    },
    {
      kind: "gold",
      date: "2014 — 2018",
      title: "B.S. Computer Science",
      org: "University of Texas at Austin",
      detail: "Concentration in systems & networking. Captain, Collegiate CTF team — 3× regional champions. Undergraduate research in TLS protocol analysis.",
    },
    {
      kind: "purple",
      date: "2017 (Summer)",
      title: "SANS SEC560 — Enterprise Penetration Testing",
      org: "SANS Institute",
      detail: "Intensive in-person training. Foundation for GCIH and OSCP track. Capstone CTF — placed 2nd of 38.",
    },
  ],
  courses: [
    { name: "Advanced Web Attacks and Exploitation (AWAE / OSWE)", platform: "Offensive Security", year: "2024", status: "done" },
    { name: "Red Team Ops II",                                     platform: "Zero-Point Security", year: "2024", status: "progress" },
    { name: "Cloud Pentesting (PEN-210 prep)",                     platform: "TCM Security",        year: "2024", status: "done" },
    { name: "Practical Malware Analysis & Triage (PMAT)",          platform: "TCM Security",        year: "2023", status: "done" },
    { name: "AWS Security Engineering",                            platform: "A Cloud Guru",        year: "2023", status: "done" },
    { name: "Kubernetes Goat Hands-On",                            platform: "Self-paced",          year: "2023", status: "done" },
    { name: "eBPF for Security",                                   platform: "Isovalent",           year: "2023", status: "done" },
    { name: "Cryptography I & II",                                 platform: "Stanford / Coursera", year: "2022", status: "done" },
    { name: "Mobile Application Penetration Testing",              platform: "INE",                 year: "2022", status: "done" },
    { name: "Linux Privilege Escalation",                          platform: "TryHackMe",           year: "2021", status: "done" },
    { name: "Active Directory Pentesting",                         platform: "HackTheBox Academy",  year: "2022", status: "done" },
    { name: "Reverse Engineering with Ghidra",                     platform: "HTB Academy",         year: "2023", status: "done" },
    { name: "Threat Modeling: A Practical Guide",                  platform: "OWASP",               year: "2022", status: "done" },
    { name: "Secure Coding in Go",                                 platform: "Pluralsight",         year: "2022", status: "done" },
    { name: "Web Security Academy — All Labs",                     platform: "PortSwigger",         year: "2021", status: "done" },
    { name: "Burp Suite Certified Practitioner",                   platform: "PortSwigger",         year: "2022", status: "done" },
    { name: "Ansible for Security Engineers",                      platform: "Red Hat",             year: "2021", status: "done" },
    { name: "Terraform Associate",                                 platform: "HashiCorp",           year: "2021", status: "done" },
    { name: "Building Secure APIs",                                platform: "Frontend Masters",    year: "2024", status: "done" },
    { name: "Hardware Hacking — IoT Firmware",                     platform: "Self-paced",          year: "2023", status: "done" },
    { name: "SLSA & Software Supply Chain Security",               platform: "OpenSSF",             year: "2024", status: "progress" },
    { name: "Detection Engineering Fundamentals",                  platform: "Splunk / Antisyphon", year: "2024", status: "progress" },
  ],
  navLinks: [
    { id: "home",        label: "home" },
    { id: "about",       label: "about" },
    { id: "skills",      label: "skills" },
    { id: "projects",    label: "projects" },
    { id: "achievements",label: "achievements" },
    { id: "education",   label: "education" },
    { id: "homelab",     label: "homelab" },
    { id: "contact",     label: "contact" },
  ],
};

window.PORTFOLIO = PORTFOLIO;
