/* Portfolio content — easily editable defaults */
const PORTFOLIO = {
  identity: {
    name: "AARON ARCHER",
    handle: "aaron_archer",
    host: "architsec",
    title: "Cybersecurity Analyst & Security Operations",
    tagline: "Securing systems. Hardening pipelines. Engineering trust.",
    bio: "Twenty years in physical security — from event and venue operations and personal protection to security management — alongside a decade as a Firefighter/EMT, including five years as Director of Operations for a 501c3 wilderness EMS agency. In that role I built and led 100+ volunteers, deployed fully-stocked field hospitals at 10,000–30,000-person events, and coordinated with county emergency management and regional EMS resources. That background — operational discipline, adversary mindset, and incident command under pressure — shapes how I approach cybersecurity. Now focused on monitoring and defending environments: building detection infrastructure, hardening cloud and on-prem systems, and closing the security gaps that real-world experience teaches you to look for. Currently completing an AAS in Cybersecurity at Red Rocks Community College.",
    location: "Remote · Worldwide",
    status: "Available for new engagements",
  },
  contact: [
    { label: "Email",    icon: "envelope",  value: "aaron.archer.emt@gmail.com",            href: "mailto:aaron.archer.emt@gmail.com" },
    { label: "GitHub",   icon: "github",    value: "github.com/anxzik",                     href: "https://github.com/anxzik" },
    { label: "LinkedIn", icon: "linkedin",  value: "linkedin.com/in/aaron-archer-69423594", href: "https://www.linkedin.com/in/aaron-archer-69423594/" },
  ],
  rotatingRoles: [
    "Cybersecurity Analyst",
    "Secure Software Developer",
    "DevSecOps Engineer",
    "Comms Security Specialist",
  ],
  stats: [
    { value: "IBM",  unit: "",        label: "Cybersecurity Analyst Cert" },
    { value: "2",    unit: "",        label: "CTF Competitions" },
    { value: "10",   unit: "+",       label: "Home Lab Projects" },
    { value: "A",    unit: " grade",  label: "Security+ & Network+ Coursework" },
    { value: "2028", unit: "",        label: "AAS Cybersecurity (exp.)" },
  ],
  skills: [
    {
      title: "Security Operations",
      sub: "Blue team · SIEM · Threat detection",
      icon: "shield-check",
      items: [
        { name: "Wazuh / ELK Stack",              level: 75 },
        { name: "Log Analysis & Triage",           level: 72 },
        { name: "Custom Detection Rules",          level: 68 },
        { name: "Sysmon / Windows Event Logging",  level: 70 },
        { name: "Incident Response Fundamentals",  level: 65 },
      ],
      tags: ["SIEM", "ELK", "Sysmon", "Detection Engineering", "Blue Team"],
    },
    {
      title: "Cloud Security",
      sub: "GCP · Kubernetes hardening",
      icon: "cloud-lock",
      items: [
        { name: "GCP (PostgreSQL, IAM, Hardening)", level: 70 },
        { name: "Kubernetes / K3s Security",        level: 72 },
        { name: "Container Image Scanning",         level: 68 },
        { name: "HashiCorp Vault",                  level: 65 },
        { name: "Harbor Registry Security",         level: 62 },
      ],
      tags: ["GCP", "K3s", "Cilium", "Vault", "Keycloak"],
    },
    {
      title: "DevSecOps",
      sub: "Shift-left · Pipeline security",
      icon: "diagram-3",
      items: [
        { name: "GitLab CI/CD",           level: 75 },
        { name: "Docker / Containers",    level: 72 },
        { name: "SAST / SCA Scanning",    level: 65 },
        { name: "Infrastructure as Code", level: 68 },
        { name: "Secret Management",      level: 65 },
      ],
      tags: ["GitLab CI", "Trivy", "Docker", "Proxmox", "Self-Hosted"],
    },
    {
      title: "Infrastructure & Networking",
      sub: "Segmentation · VPN · Active Directory",
      icon: "hdd-network",
      items: [
        { name: "Windows Server / Active Directory", level: 78 },
        { name: "WireGuard VPN + MFA",               level: 80 },
        { name: "Network Segmentation / VLANs",      level: 72 },
        { name: "Proxmox VE Virtualization",          level: 78 },
        { name: "Firewall Configuration",             level: 70 },
      ],
      tags: ["Windows Server", "WireGuard", "Proxmox", "AD", "Zero-Trust"],
    },
    {
      title: "Languages & Runtime",
      sub: "Polyglot by practice",
      icon: "code-slash",
      items: [
        { name: "Python",      level: 75 },
        { name: "Bash",        level: 78 },
        { name: "Go",          level: 65 },
        { name: "JavaScript",  level: 68 },
        { name: "Java",        level: 60 },
      ],
      tags: ["FastAPI", "React", "Node", "PowerShell", "Rust"],
    },
    {
      title: "Comms Security",
      sub: "OPSEC · Encrypted channels",
      icon: "broadcast-pin",
      items: [
        { name: "WireGuard / VPN Architecture", level: 80 },
        { name: "End-to-End Encryption",        level: 72 },
        { name: "OPSEC Principles",             level: 78 },
        { name: "ATAK / CoT Protocol",          level: 70 },
        { name: "MFA / Hardware Tokens",        level: 72 },
      ],
      tags: ["TLS 1.3", "WireGuard", "ATAK", "CoT", "Mattermost"],
    },
  ],
  projects: [
    {
      name: "PyNMAP — Automated Network Enumeration Tool",
      year: "2025",
      status: "complete",
      category: "softwaredev",
      description: "Python-based automated NMAP enumeration tool developed as the final project for Fundamentals of Computer Programming at RRCC. Executes structured network scans and writes all results to an organized output file for analysis and reporting.",
      tags: ["Python", "Nmap", "Network Enumeration", "Automation", "CLI"],
      links: [{ label: "github", href: "https://github.com/anxzik/PyNmap" }],
    },
    {
      name: "Network Planner",
      year: "2025",
      status: "ongoing",
      category: "networking",
      description: "Network topology planning and documentation tool for designing segmented network architectures. Supports structured planning of VLANs, subnetting, and access control zones for home lab and small enterprise environments.",
      tags: ["Networking", "Network Design", "Topology", "Segmentation", "Documentation"],
      links: [{ label: "github", href: "https://github.com/anxzik/network-planner" }],
    },
    {
      name: "Active Directory Homelab — Redundancy and Failover",
      year: "2024",
      status: "ongoing",
      category: "devsecops",
      description: "Physical server configuration for a home lab Active Directory environment with high availability, redundancy, and failover capabilities. Includes domain controller replication, group policy hardening, and disaster recovery validation.",
      tags: ["Windows Server", "PowerShell", "Active Directory", "Redundancy", "Failover"],
      links: [],
    },
    {
      name: "GitLab CI/CD Pipeline for Secure Software Delivery",
      year: "2026",
      status: "ongoing",
      category: "devsecops",
      description: "Self-hosted GitLab CI/CD pipeline with integrated security scanning, compliance checks, and artifact signing. Currently serving as the delivery infrastructure for REDLINE development on on-prem Proxmox servers.",
      tags: ["Self-Hosted", "CI/CD", "Secure Code Review", "Supply Chain Security", "GitLab CI"],
      links: [],
    },
    {
      name: "Proxmox VE Home Lab — Self-Hosted Services, Secret Management, Encrypted Comms",
      year: "2026",
      status: "complete",
      category: "devsecops",
      description: "Proxmox VE home lab running secure self-hosted services including a CI/CD pipeline, HashiCorp Vault for secret management, and Mattermost for end-to-end encrypted internal communications.",
      tags: ["Self-Hosted", "Docker", "Kubernetes", "Mattermost", "Proxmox VE", "Vault"],
      links: [],
    },
    {
      name: "Kubernetes Dev Environment — K3s, Vault, Cilium, Harbor, Keycloak",
      year: "2026",
      status: "ongoing",
      category: "cloud",
      description: "Lightweight Kubernetes development environment using K3s with production-grade security: Vault for secret management, Cilium for eBPF-based network policy enforcement, Harbor for container image scanning, and Keycloak for identity and access management.",
      tags: ["Kubernetes", "K3s", "Harbor", "Cilium", "Vault", "Keycloak", "Terraform"],
      links: [],
    },
    {
      name: "REDLINE — Realtime Emergency Dispatch, Logistics & Intelligence Engine",
      year: "2025",
      status: "ongoing",
      category: "softwaredev",
      description: "Production emergency dispatch and field coordination platform built from 10 years of operational EMS experience. Core CAD engine, API gateway, and frontend scaffolding functional. Architecture spans HIPAA, CJIS, and FedRAMP compliance, TAK/CoT integration, P25 radio bridging, and multi-protocol communications. CI/CD and Kubernetes infrastructure in active development.",
      tags: ["Go", "React", "HIPAA", "CJIS", "ATAK", "CoT", "P25", "PostgreSQL", "Kafka"],
      links: [{ label: "architecture diagram", href: "https://gist.github.com/anxzik/00c33b56aba3569a611a9dd5531dfa82" }],
    },
    {
      name: "Wazuh SIEM — ELK Stack, Sysmon, and Custom Detection Rules",
      year: "2025",
      status: "ongoing",
      category: "blue team",
      description: "Wazuh security monitoring platform deployed on Proxmox VE, integrated with the ELK stack for log aggregation and analysis. Includes Sysmon for enhanced endpoint visibility and custom detection rules for identifying threats and anomalies in the home lab environment.",
      tags: ["Wazuh", "ELK Stack", "SIEM", "Sysmon", "Log Management", "Detection Rules"],
      links: [],
    },
    {
      name: "WireGuard VPN — MFA and Dynamic DNS for Home Lab Remote Access",
      year: "2024",
      status: "complete",
      category: "devsecops",
      description: "WireGuard VPN with multi-factor authentication and dynamic DNS for secure remote access to home lab infrastructure. Ensures authenticated, encrypted access while supporting flexible network addressing.",
      tags: ["WireGuard", "VPN", "MFA", "Dynamic DNS", "Zero-Trust"],
      links: [],
    },
    {
      name: "Architsec Network Architecture — Zero-Trust, Segmentation, Endpoint Security",
      year: "2022",
      status: "complete",
      category: "networking",
      description: "Corporate network architecture design applying zero-trust principles, network segmentation to limit lateral movement, and layered endpoint security controls to protect against unauthorized access.",
      tags: ["Network Architecture", "Zero-Trust", "Network Segmentation", "Endpoint Security"],
      links: [],
    },
  ],
  certifications: [
    { name: "IBM Cybersecurity Analyst Professional Certificate", org: "IBM & Coursera", year: "2022", icon: "bullseye" },
    { name: "ISC2 Certified in Cybersecurity (CC)",               org: "ISC2",           year: "2023", icon: "patch-check",   expired: true },
    { name: "EC-Council Cybersecurity Technician (CCT)",          org: "EC-Council",     year: "2024", icon: "shield-shaded", expired: true },
  ],
  achievements: [
    "Contributor to DoD ATAK-CIV — fixed legacy sun.security certificate signing failures blocking admin cert installation; improved multi-architecture deployment compatibility",
    "NCL Cyber Skyline CTF 2025 — Individual competitor",
    "Magnet Forensics CTF 2026 — Individual competitor, digital forensics",
    "Director of Operations — 501c3 Wilderness EMS Agency · 100+ volunteers · field hospitals at 10k–30k person events · county EMS interoperability",
  ],
  education: [
    {
      kind: "teal",
      date: "2025 — Current",
      title: "AAS Cybersecurity",
      org: "Red Rocks Community College · Lakewood, CO",
      detail: "In-person coursework with hands-on labs. Focus on network security, incident response, and ethical hacking. Expected graduation: 2028.",
    },
    {
      kind: "gold",
      date: "2018 — 2019",
      title: "IBM Cybersecurity Analyst Professional Certificate",
      org: "IBM & Coursera",
      detail: "Comprehensive online program covering cybersecurity fundamentals, network security, incident response, and threat intelligence. Capstone project: developed a secure web application with integrated vulnerability scanning.",
    },
    {
      kind: "purple",
      date: "2019 — 2020",
      title: "ISC2 Certified in Cybersecurity (CC)",
      org: "ISC2",
      detail: "Vendor-neutral certification covering cybersecurity principles, risk management, and security operations. Expired 2023.",
    },
    {
      kind: "orange",
      date: "2020 — 2021",
      title: "EC-Council Cybersecurity Technician (CCT)",
      org: "EC-Council",
      detail: "Entry-level certification focused on cybersecurity operations, network defense, and ethical hacking. Expired 2024.",
    },
    {
      kind: "green",
      date: "2021 — Current",
      title: "Cisco Netacademy — Cybersecurity and Networking",
      org: "Cisco Systems · Online",
      detail: "Ongoing self-directed learning through Cisco's Netacademy platform. Completed courses in cybersecurity, networking, and IoT security.",
    },
  ],
  courses: [
    { name: "Cybersecurity Skills & SOC Training",                    platform: "RangeForce",        year: "2026", status: "progress" },
    { name: "Cybersecurity Learning Paths",                           platform: "TryHackMe",         year: "2026", status: "progress" },
    { name: "Digital Forensics",                                      platform: "RRCC / EC-Council",  year: "2026", status: "progress" },
    { name: "Fundamentals of Computer Programming",                   platform: "RRCC",              year: "2025", status: "done" },
    { name: "Fundamentals of Computer Networking — CompTIA Network+", platform: "RRCC / CompTIA",    year: "2025", status: "done" },
    { name: "Fundamentals of Cybersecurity — CompTIA Security+",      platform: "RRCC / CompTIA",    year: "2025", status: "done" },
    { name: "Hardware Hacking — IoT Firmware",                        platform: "Self-paced",        year: "2023", status: "done" },
  ],
  navLinks: [
    { id: "home",         label: "home" },
    { id: "about",        label: "about" },
    { id: "skills",       label: "skills" },
    { id: "projects",     label: "projects" },
    { id: "achievements", label: "achievements" },
    { id: "education",    label: "education" },
    { id: "contact",      label: "contact" },
  ],
};

window.PORTFOLIO = PORTFOLIO;
